Add Angular elements and web component build
hubmapconsortium/tissue-bar-graphs pull request #2
Opened 2022-01-10 15:16 UTC by amberramesh

- Add scripts for packing/concatenating web component
- Add module for creating wc
- Add service to append wc to app root

2022-01-10 15:34 UTC, bherr2 requested changes
Also, you need to update/add instructions for embedding the component to the README.md

2022-01-10 15:34 UTC, bherr2 commented on src/app/app.component.html
> +<div id="app"></div>
Why can't you use the cns tissue block web component here? Also you don't need id="app" (bad practice in Angular)

2022-01-10 15:34 UTC, bherr2 commented on src/app/app.component.ts
> +    this.titleService.setTitle('CNS Tissue Blocks')
Remove this and just set the title in the index.html

2022-01-10 15:34 UTC, bherr2 commented on src/app/app.component.ts
> +  title = 'tissue-blocks'
Remove this and just set the title in the index.html

2022-01-10 15:34 UTC, bherr2 commented on src/app/app.component.ts
> +    this.tissueBlockService.injectElement()
You shouldn't need to do this. You should be able to just use the custom element in your app.component.html

2022-01-10 15:34 UTC, bherr2 commented on src/app/services/tissue-blocks.service.ts
> +export class TissueBlocksService {
Don't do this.

2022-01-10 15:42 UTC, amberramesh commented on src/app/app.component.html
> +<div id="app"></div>
Updated to using web component directly (along with related changes).

2022-01-10 15:43 UTC, amberramesh commented on src/app/app.component.ts
> +    this.tissueBlockService.injectElement()
Have set the document title instead of using service.

2022-01-14 14:20 UTC, amberramesh commented
>

2022-01-14 14:40 UTC, bherr2 approved these changes

2022-01-14 14:43 UTC, merged